swagger: '2.0'
info:
  title: Jokes MCP Server
  description: Get jokes using MCP server. For instance Chuck Norris jokes, Dad jokes and Yo Mama jokes.
  version: 1.0.0
host: <mcp server url>
basePath: /
schemes:
  - https
paths:
  /mcp:
    post:
      summary: Jokes MCP Server
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: InvokeMCP
      responses:
        '200':
          description: Success
securityDefinitions: {}
